services:
  - type: web
    name: line-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000"
